# Generated by Django 2.2.1 on 2019-06-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soildata',
            old_name='moisture',
            new_name='moisture1',
        ),
        migrations.AddField(
            model_name='soildata',
            name='moisture2',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soildata',
            name='moisture3',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
