version: '3.5'


services:
  napoleon:
    image: api
    hostname: napoleon
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: inv db run
    ports:
      - "8001:8000"
    volumes:
      - ./src/:/src/