version: '3.5'


services:
  napoleon:
    image: api
    hostname: napoleon
    networks:
      - ricc-network
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: inv db run
    ports:
      - "4600:4600"
    volumes:
      - ./src/:/src/

networks:
  ricc-network:
    driver: bridge