version: '3.5'


services:
  django:
    image: api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: db run
    ports:
      - "8000:8000"
    volumes:
      - ./src/:/src/
    networks:
      - ricc-network

networks:
  ricc-network:
    driver: bridge
