version: '3.5'


services:
  django:
    image: api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: inv db run
    ports:
      - "8080:8000"
    volumes:
      - ./src/:/src/
